### ISSUE TITLE
How to parse '{"proj": "aea", "lat_1": 25, "lat_2": 47, "lat_0": 0, "lon_0": 105, "x_0": 0, "y_0": 0, "datum": "WGS84", "units": "m", "no_defs": true}'

### ISSUE THREAD

**Issue by wsf1990** [karimbahgat/PyCRS#41] opened 2019-06-23 04:18 UTC
How can I parse a projection like this:
```
{"proj": "aea", "lat_1": 25, "lat_2": 47, "lat_0": 0, "lon_0": 105, "x_0": 0, "y_0": 0, "datum": "WGS84", "units": "m", "no_defs": true}
```

**Comment by micahcochran** [comment] 2019-06-24 20:03
That is a proj4 dictonary ([see this](https://github.com/karimbahgat/PyCRS#parsing-from-proj4-string-or-dict)).

Does that solve your problem?

**Comment by wsf1990** [comment] 2019-06-25 01:46
@micahcochran Thanks，I'd found this.But this API told me no `ellps`. So must I add the `ellps` parameter to this proj4? Now I take the `datum` parameter and put it to `ellps`.

**Comment by micahcochran** [comment] 2019-06-25 13:38
If you show us a short snippet of code that reproduces the problem. Then show what error message is popping up.  We might be able to figure out if there is a problem with the bad input or if the problem is with PyCRS.

For `proj=aea`, the [`ellps` parameter is optional](https://proj.org/operations/projections/aea.html) in PROJ 6.1.0.

**Comment by wsf1990** [comment] 2019-06-25 13:43
@micahcochran Thanks！
This is my code snippet:
```
src = '{"proj": "aea", "lat_1": 25, "lat_2": 47, "lat_0": 0, "lon_0": 105, "x_0": 0, "y_0": 0, "datum": "WGS84", "units": "m", "no_defs": true}'
print(pycrs.parse.from_proj4(json.loads(src)))
```
And this is what the error is:
```
  File "**\site-packages\pycrs\parse.py", line 544, in from_proj4
    raise FormatError("The format string is missing the required +ellps element, or the alternative manual specification of the +a with +b or +f/+rf elements: \n\t %s" % partdict)
pycrs.parse.FormatError: The format string is missing the required +ellps element, or the alternative manual specification of the +a with +b or +f/+rf elements: 
	 {'+proj': 'aea', '+lat_1': 25, '+lat_2': 47, '+lat_0': 0, '+lon_0': 105, '+x_0': 0, '+y_0': 0, '+datum': 'WGS84', '+units': 'm', '+no_defs': True}
```

**Comment by wsf1990** [comment] 2019-07-02 09:03
Hi,
I found a new issue,I have a location which is `(lon, lat) (215018.25, 4824066.75)`, and the crs is `EPSG:32650`. When I transform this location to `epsg:4326` use this code:
```
lon, lat = 215018.25, 4824066.75
    to_proj = pycrs.parse.from_ogc_wkt('GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]').to_proj4()
    from_proj = pycrs.parse.from_epsg_code(32650).to_proj4()
    print(to_proj)
    print(from_proj)
    t_lon, t_lat = pyproj.transform(pyproj.Proj(from_proj), pyproj.Proj(to_proj), lon, lat)
    print(t_lon, t_lat)
```
I got this result: `-6.5258322207676605 43.51516233549309`.

Which the lat is right, but the lon is wrong,I think the question is located in the center of Longitude.

**Comment by karimbahgat** [comment] 2019-07-15 14:22
To answer @wsf1990 , yes pycrs complains because it needs to know the ellipse which is missing. However, the specification of the datum in this case does carry with it an implied ellipsoid, which PyCRS was supposed to use, but I see now it failed to do so. I have fixed now so that it defaults to the implied datum ellipsoid when it's not explicitly set and will include this in the next version.

**Comment by wsf1990** [comment] 2019-07-16 01:25
Got it,Thanks!

**Comment by karimbahgat** [comment] 2020-03-09 12:33
Next version v1.0.2 which fixes this finally up on pypi.

**Closed by karimbahgat** 2020-03-09 12:33 UTC
Labels: bug

**Comment by karimbahgat** [comment] 2020-03-09 12:58
I.e. this works:

```
>>> proj4_dict = {"proj": "aea", "lat_1": 25, "lat_2": 47, "lat_0": 0, "lon_0": 105, "x_0": 0, "y_0": 0, "datum": "WGS84", "units": "m", "no_defs": 'true'}
>>> crs = pycrs.parse.from_proj4(proj4_dict)
>>> print(crs.geogcs.datum.ellips)
<pycrs.elements.datums.WGS84 instance at 0x0000000005589A88>
```
